# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regex_redirects', '0002_auto_20151217_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set([('old_path', 'new_path', 'fallback_redirect')]),
        ),
    ]
